### PR TITLE
Pass FormData in as-is

### LINKED ISSUE #10: FormData handling
I believe right now sending FormData is broken as we are always stringifying the payload. 

I believe we want to check if the payload is `FormData` and if so, pass it as-is:

```ts
payload: payload instanceof FormData ? payload : JSON.stringify(payload)
```

We should add tests to assert this expected behavior. 

This is a placeholder for that work.

### PR DESCRIPTION
**Pull request by danawoodman**
- Add support for passing in `FormData` as-is instead of `JSON.stringify`ing it as we do now. Should only add a few bytes to the final bundle
- Add tests for passing in `FormData`
- Big refactoring of tests

Closes #10

### CODE REVIEW

**Comment by weepy** [comment]
i did this!

**Comment by Crisfole** [comment]
@danawoodman you need to stub in FormData or run it in an environment like MiniFlare or CF Workerd where FormData is stubbed in for you.

**Comment by danawoodman** [comment]
@Crisfole Why would it not need to be stubbed locally tho? I'm running the same build/test commands

**Comment by danawoodman** [comment]
This also brings up a question: if FormData isn't available, itty-fetcher will fail; what can we do about that?

**Comment by Crisfole** [comment]
`Request` is also not globally available. Nor is `Response`. This is Not Your Problem:tm:.

image

**Comment by danawoodman** [comment]
I assume fetch would fail if those aren't available anyways, without some kind of poly fill/override. 

Now how do we fix these tests since they work fine locally?

**Comment by Crisfole** [comment]
@danawoodman what's your local env like? (Node version?)

**Comment by kwhitley** [comment]
Yeah, same issue... pulled this in an hit with FormData immediately. 
image

**Sources confirming general browser/worker availability**
- https://caniuse.com/?search=FormData
- https://developer.mozilla.org/en-US/docs/Web/API/FormData

**Questions**
- Node (and other runtime) compatibility?

### Suggested Path
If this works fine in most of those runtimes without polyfills, I'd say we add the supporting types to the `tsconfig.json` and bypass this issue ourselves.  Leave a requirement to polyfill if the user's runtime doesn't support it.  Conversely we try/catch, but...

**Comment by Crisfole** [comment]
This will work in SK, Workers, Pages, it will work in > Node 18:

image

That screenshot is from just after `nvm install v18`

**Comment by danawoodman** [comment]
I must be using 18. Will confirm when I'm home

**Comment by danawoodman** [comment]
@kwhitley I've updated the actions to use Node 18 (fixes actions), added a `.node-version` file to set that locally and added some notes in the readme. I think this is ready for your review!

Thanks @Crisfole for pointing me to the solution!

**Comment by kwhitley** [comment]
This is awesome, only comment is that thing about 18.0.0 vs 18.10.0, but i'll merge and tweak that :)

**Comment by danawoodman** [comment]
@kwhitley thanks! I didn't see a note on 18, what was your question? 18.10.0 is the latest version so I opted for that for local dev. The actual action runs on anything 18+ which I think is ok

**Pull request merged**
